# Generated by Django 5.2.6 on 2025-09-21 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapi', '0002_trainingdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrainingData',
        ),
    ]
