# Generated by Django 5.2.6 on 2025-09-21 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapi', '0003_delete_trainingdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('question_type', models.CharField(choices=[('corporate_culture', 'Корпоративная культура'), ('general', 'Общие вопросы')], default='general', max_length=20, verbose_name='Тип вопроса')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
